### ISSUE TITLE
Dot not rerun `build.rs` very often

### ISSUE THREAD

**Issue by toyboot4e** [toyboot4e/rokol#4]
When I use `rokol` as a git dependency, somehow `rokol_ffi/build.rs` is always run:

```toml
[dependency]
rokol = { git = "https://github.com/toyboot4e/rokol", features = ["glcore33"] }
```

When I use `rokol` as a local crate, it doesn't happen:

```toml
[dependency]
rokol = { path = "rokol" }
```
